const ArticleData = [
    {
    field: 'Desarrollo',
    category: ["Fundamentos"],
    image: '/assets/blog-assets/LasComputadorasSoloEntienden0y1/LasComputadorasSoloEntienden0y1.webp',
    title: '¿Por qué las computadoras solo entienden 0 y 1?',
    date:'Abril 23, 2025',
    url: 'LasComputadorasSoloEntienden0y1',
    },
    {
    field: 'Desarrollo',
    category: ["JavaScript"],
    image: '/assets/blog-assets/JavaScript/MetodosArraysJavaScript.webp',
    title: 'Métodos de un array en JavaScript',
    date:'Noviembre 21, 2022',
    url: 'MetodosArrayJavaScript',
    },
    {
    field: 'Desarrollo',
    category: ["JavaScript"],
    image: '/assets/blog-assets/JavaScript/FuncionesJavaScript.webp',
    title: '4 Formas de escribir una función en JavaScript',
    date:'Noviembre 20, 2022',
    url: 'FuncionesJavaScript',
    },
    {
    field: 'Desarrollo',
    category: ["Tailwind"],
    image: '/assets/blog-assets/RecursosTailwind/ResourseTailwind.webp',
    title: 'Colección de recursos para Tailwind',
    date:'Septiembre 07, 2022',
    url: 'ColeccionRecursosTailwind',
    },
    {
    field: 'Desarrollo',
    category: ["Herramientas"],
    image: '/assets/blog-assets/LibrosDesarrolladores/LibrosDesarrolladores.webp',
    title: 'Mejores libros para desarrolladores',
    date:'Septiembre 06, 2022',
    url: 'MejoresLibrosDesarrolladores',
    },
    {
    field: 'Desarrollo',
    category: ["HTML"],
    image: '/assets/blog-assets/HTML.webp',
    title: 'Etiquetas HTML esenciales que debes conocer',
    date:'Julio 25, 2022',
    url: 'EtiquetasHTMLEsenciales',
    },
    {
    field: 'Desarrollo',
    category: ["Herramientas"],
    image: '/assets/blog-assets/Chrome103/Devtools.webp',
    title: 'Novedades en DevTools (Chrome 103)',
    date:'Julio 24, 2022',
    url: 'DevToolsChrome103',
    },
    
// TECNOLOGIA
    {
    field: 'Tecnología',
    category: ['Google'],
    image: '/assets/blog-assets/GooglePixel10/Pixel10MadebyGoogle.webp',
    title: 'Pixel 10 y Gemini: el dúo con el que Google planea dominar el 2025',
    date:'Agosto 6, 2025',
    url: 'Pixel10MadebyGoogle',
    },
    {
    field: 'Tecnología',
    category: ['Periféricos'],
    image: '/assets/blog-assets/AsusRogAzoth/AsusRogAzoth.webp',
    title: 'ASUS ROG Azoth: ¿el teclado gaming definitivo?',
    date:'Junio 7, 2025',
    url: 'AsusRogAzoth',
    },
    {
    field: 'Tecnología',
    category: ['Audio','Periféricos'],
    image: '/assets/blog-assets/SonyWH1000XM6/SonyWH1000XM6.webp',
    title: 'WH-1000XM6: Sony redefine el estándar en cancelación de ruido',
    date:'Mayo 28, 2025',
    url: 'SonyWH1000XM6',
    },
    {
    field: 'Tecnología',
    category: ['Consolas'],
    image: '/assets/blog-assets/LaNuevaEraDelGamingPortátil/AsusRogAlly.webp',
    title: 'La nueva era del gaming portátil: ROG Ally, Steam Deck  y Switch 2',
    date:'Abril 20, 2025',
    url: 'LaNuevaEraDelGamingPortátil',
    },
    {
    field: 'Tecnología',
    category: ['Consolas'],
    image: '/assets/blog-assets/NintendoSwitch2/NintendoSwitch2.webp',
    title: 'Nintendo Switch 2 ya es oficial, y viene con todo',
    date:'Abril 14, 2025',
    url: 'NintendoSwitch2',
    },
    {
    field: 'Tecnología',
    category: ['Laptops'],
    image: '/assets/blog-assets/ZenbookA14/ZenbookA14.webp',
    title: 'Zenbook A14 quiere destronar a la MacBook Air',
    date:'Abril 8, 2025',
    url: 'ZenbookA14',
    },
    {
    field: 'Tecnología',
    category: ['Periféricos'],
    image: '/assets/blog-assets/MejoresRatonesGaming2022/MejoresRatonesGaming2022.webp',
    title: 'Mejores Ratones Gaming 2022',
    date:'Agosto 18, 2022',
    url: 'MejoresRatonesGaming2022',
    },

// APPLE
    {
    field: 'Apple',
    category: ['iPhone','MacBook','Watch','Vision Pro','iOS','Apple Intelligence','WWDC'],
    image: '/assets/blog-assets/WWDC2025NovedadesyRumores/WWDC25.webp',
    title: 'WWDC 2025: Todas las novedades confirmadas y los rumores más fuertes',
    date:'Mayo 29, 2025',
    url: 'WWDC2025NovedadesyRumores',
    },
    {
    field: 'Apple',
    category: ['iPhone', 'Apple Intelligence'],
    image: '/assets/blog-assets/iPhone17air/iPhone17air.webp',
    title: 'iPhone 17 Air: el modelo más delgado en la historia de Apple',
    date:'Abril 17, 2025',
    url: 'iPhone17air',
    },
    {
    field: 'Apple',
    category: ['iPhone', 'Apple Intelligence'],
    image: '/assets/blog-assets/iPhone17pro/iPhone17pro8K.webp',
    title: 'Grabar en 8K desde un iPhone: el 17 Pro lo haría posible',
    date:'Abril 11, 2025',
    url: 'iPhone17Pro8K',
    },
    {
    field: 'Apple',
    category: ['iPhone', 'iOS', 'Apple Intelligence'],
    image: '/assets/blog-assets/iOS184/iOS184.webp',
    title: 'Novedades de iOS 18.4',
    date:'Abril 5, 2025',
    url: 'NovedadesiOS184',
    },
    {
    field: 'Apple',
    category: ['MacBook'],
    image: '/assets/blog-assets/MacBookAirM2Review/MacBookAirM2Review.webp',
    title: 'MacBook Air M2 review',
    date:'Agosto 14, 2022',
    url: 'MacBookAirM2Review',
    },
]

export default ArticleData
