const ArticleData = [
    {
    field: 'Desarrollo',
    category: ["JavaScript"],
    image: '/assets/blog-assets/JavaScript/MetodosArraysJavaScript.webp',
    title: 'Métodos de un array en JavaScript',
    date:'Noviembre 21, 2022',
    url: 'MetodosArrayJavaScript',
    },
    {
    field: 'Desarrollo',
    category: ["JavaScript"],
    image: '/assets/blog-assets/JavaScript/FuncionesJavaScript.webp',
    title: '4 Formas de escribir una función en JavaScript',
    date:'Noviembre 20, 2022',
    url: 'FuncionesJavaScript',
    },
    {
    field: 'Desarrollo',
    category: ["Tailwind"],
    image: '/assets/blog-assets/RecursosTailwind/ResourseTailwind.webp',
    title: 'Colección de recursos para Tailwind',
    date:'Septiembre 07, 2022',
    url: 'ColeccionRecursosTailwind',
    },
    {
    field: 'Desarrollo',
    category: ["Herramientas"],
    image: '/assets/blog-assets/LibrosDesarrolladores/LibrosDesarrolladores.webp',
    title: 'Mejores libros para desarrolladores',
    date:'Septiembre 06, 2022',
    url: 'MejoresLibrosDesarrolladores',
    },
    {
    field: 'Desarrollo',
    category: ["HTML"],
    image: '/assets/blog-assets/HTML.webp',
    title: 'Etiquetas HTML esenciales que debes conocer',
    date:'Julio 25, 2022',
    url: 'EtiquetasHTMLEsenciales',
    },
    {
    field: 'Desarrollo',
    category: ["Herramientas"],
    image: '/assets/blog-assets/Chrome103/Devtools.webp',
    title: 'Novedades en DevTools (Chrome 103)',
    date:'Julio 24, 2022',
    url: 'DevToolsChrome103',
    },
    
// TECNOLOGIA
    {
    field: 'Tecnología',
    category: ['Consolas'],
    image: '/assets/blog-assets/NintendoSwitch2/NintendoSwitch2.webp',
    title: 'Nintendo Switch 2 ya es oficial, y viene con todo',
    date:'Abril 14, 2025',
    url: 'NintendoSwitch2',
    },
    {
    field: 'Tecnología',
    category: ['Laptops'],
    image: '/assets/blog-assets/ZenbookA14/ZenbookA14.webp',
    title: 'Zenbook A14 quiere destronar a la MacBook Air',
    date:'Abril 8, 2025',
    url: 'ZenbookA14',
    },
    {
    field: 'Tecnología',
    category: ['Periféricos'],
    image: '/assets/blog-assets/MejoresRatonesGaming2022/MejoresRatonesGaming2022.webp',
    title: 'Mejores Ratones Gaming 2022',
    date:'Agosto 18, 2022',
    url: 'MejoresRatonesGaming2022',
    },

// APPLE
    // {
    // field: 'Apple',
    // category: ['iPhone', 'Apple Intelligence'],
    // image: '/assets/blog-assets/iPhone17air/iPhone17air.webp',
    // title: 'iPhone 17 Air: el modelo más delgado en la historia de Apple',
    // date:'Abril 17, 2025',
    // url: 'iPhone17air',
    // },
    {
    field: 'Apple',
    category: ['iPhone', 'Apple Intelligence'],
    image: '/assets/blog-assets/iPhone17pro/iPhone17pro8K.webp',
    title: 'Grabar en 8K desde un iPhone: el 17 Pro lo haría posible',
    date:'Abril 11, 2025',
    url: 'iPhone17Pro8K',
    },
    {
    field: 'Apple',
    category: ['iPhone', 'iOS', 'Apple Intelligence'],
    image: '/assets/blog-assets/iOS184/iOS184.webp',
    title: 'Novedades de iOS 18.4',
    date:'Abril 5, 2025',
    url: 'NovedadesiOS184',
    },
    {
    field: 'Apple',
    category: ['MacBook'],
    image: '/assets/blog-assets/MacBookAirM2Review/MacBookAirM2Review.webp',
    title: 'MacBook Air M2 review',
    date:'Agosto 14, 2022',
    url: 'MacBookAirM2Review',
    },
]

export default ArticleData